name: Expo EAS Build (Android)

on:
  push:
    branches: [ main ]

jobs:
  eas-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm # or yarn, if you use yarn
          cache-dependency-path: package-lock.json # or yarn.lock

      - name: Install dependencies
        run: |
          npm ci # Use npm ci for clean installs in CI/CD environments
          # If you use yarn: yarn install --frozen-lockfile

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Start EAS Build
        run: eas build --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}